### ISSUE TITLE
Auto-PTT and Auto-COS Feature (Built-in High-Performance Low Latency VOX)

### ISSUE THREAD

**Issue by skuep** [skuep/AIOC#19]
Referencing comment https://github.com/skuep/AIOC/issues/11#issuecomment-1414191015_
> I like "Auto-PTT". Nice! Before implementing this feature I would like to add a HID endpoint for configuring the AIOC. Then we can decide whether we choose the Manual-PTT (current) or the Auto-PTT as default setting. Since you said that even the SignaLink does it, I am a bit more convinced. CM119A based GPIO should be quite easy to implement btw.. If you think it's worthwhile.

The idea is to implement AIOC-based "Auto-PTT", which is basically a fancy VOX feature for digital modes, with very low latency.

Ideas/comments/feature welcome!

EDIT: Branching off of issue https://github.com/skuep/AIOC/issues/17

The "plan" from https://github.com/skuep/AIOC/issues/17#issuecomment-1552875701:

> Got ya. I have thought about how I could go about it with my slim resources. What about the following plan:
>
> 1. Implement a simple Auto-PTT and Auto-COS using a threshold of the digital data and a time-out. Is the data above the threshold, enable PTT and reset the time-out. If the time-out expires (e.g. 1ms or 10ms), disable PTT
> 1. For now, release two firmware binaries, one with Auto-PTT enabled and also the "regular" firmware (PTT via serial/CM108 only).
> 1. Profit At some point in the future, set Auto-PTT as default, if it turns out, that it is more requested, than the current default (serial/CM108). And/or include a configuration feature, where you can configure the AIOC using a python script (and a currently unused HID endpoint). Enable/Disable various PTT sources and set threshold/timeout.
>
> I know we have had this discussion before on whether we should make Auto-PTT enabled by default. But I have not yet found a decisive argument for that (except that SignaLink does it too... IIRC).

**Comment by skuep** [comment]
I started working on this feature in pull request https://github.com/skuep/AIOC/pull/25.

I implemented a very basic thresholding mechanism both on the data that is being sent and received by the AIOC. This means that with this change, you can
- Configure e.g. direwolf without any PTT mechanism. Just the soundcard. If the AIOC detects data to be sent, it activates the PTT (red light goes on). After a (currently hardcoded) timeout of 10ms, it deactivates the PTT again (red light goes off).
- Sense when analog data (i.e. more than just pure silence) is coming from the radio. If the AIOC detects any noticable volume of audio data being received by the ADC, it uses the CM108 button functionality to assert the "Volume Down" button (compatible to how AllStarLink does it) and lights up the green led. After (currently) 10ms of total silence, it deactivates the "Volume Down" button and the green led goes back to dim brightness.

I have attached a firmware file that you can use for testing purposes. Note that this is purely for testing and not a release (will follow later).

Automatic PTT (to be renamed) works quite well. Tested with direwolf. However from my testing so far there are the following issues with the Automatic COS:
- It works only, when the ADC is running, i.e. the host has to open the audio device for recording. Otherwise the AIOC disables the ADC (currently). I think this is a big issue for AllStarLink, since it probably only starts recording once it sees the COS being asserted, right?
- What imbecile (Sorry!) thought it was a good idea, to map the COS input on the "Volume-Down" button of the CM108? It interferes with the system and turns down the PC volume - for real. Why not use another GPIO... Anyway, I have taken the liberty to modify the HID report descriptor for the AIOC to account for that. This means, that the AIOC (in contrast to the CM108) will not interfere with the volume controls of the PC anymore, because I have set the reported functionality to "Unassigned" instead of "Volume Down". The operating system then just ignores the COS-messages from the AIOC. (see https://github.com/skuep/AIOC/pull/25/commits/9913eaf700bee7ac50c466c7cdcef81ef16d3f53). This of-course makes the AIOC "less compatible" to the CM108, but I currently suspect, that this is not generally an issue.
- The Automatic COS detection is a bit flaky with low or no amplitude audio. I.e. if I just push the PTT of a second radio, the green LED on the AIOC on the receiving radio flickers. However if I talk into the radio and produce some volume, the green LED stays lit. This would be something we have to test with AllStarLink to see if its an issue and how to solve it.

Feel free to play around with the new features and let me know what works for you and what doesn't. I have actually not tested this feature with real data transmission between to APRS nodes. I invite you to do so.

[aioc-fw-1.2.0-autopttcos.zip](https://github.com/skuep/AIOC/files/11524529/aioc-fw-1.2.0-autopttcos.zip)

**Comment by skuep** [comment]
Regarding the name, what about virtual PTT/COS? VPTT and VCOS?

**Comment by ITCMD** [comment]
Just cuz I like catless PTT, what about "Catless PTT" and "Autocat COS?"
OR maybe "CleanRX COS" and "CatlessTX PTT"
I will be in no way offended if you don't pick my suggestions, just thoughts!

I really appreciate your hard work on the VOX mode!

**Comment by ITCMD** [comment]
Any updates on this? How stable does the virtual ptt firmware seem to be?

**Comment by skuep** [comment]
Have not gotten any feedback so far. From my limited testing it works.. feel free to test 😁

**Comment by skuep** [comment]
@ITCMD yeah, thanks for getting him into contact with me, much appreciated 😁

What do you mean with "COS stuff that hasn't been working"? The firmware file has both the automatic PTT and COS enabled, yep.

**Comment by ITCMD** [comment]
> @ITCMD yeah, thanks for getting him into contact with me, much appreciated 😁 say thanks to him from me.
> 
> What do you mean with "COS stuff that hasn't been working"? The firmware file has both the automatic PTT and COS enabled, yep.

I think it comes from my misunderstanding of what the COS does or would be for. If it doesn't interfere with basic use of the VOX function out and receiving audio in, then it should be perfect for what we need. I'm assembling and installing the firmware on some today.

**Comment by ITCMD** [comment]
Gotchya makes sense. Flashed it and it works, although for all my HTs the rfi seems to be messing with it. It transmits for a sec then disconnects if I have more than 1w out.

Might be the usb hub vs the AIOC, however. Does make me wish the usb c port pointed down instead of up so the usb cable wasnt next to the antenna.

**Comment by ITCMD** [comment]
One new question for you since I cant test it at the moment.
Does CAT PTT still work when using the automatic ptt software?

**Comment by skuep** [comment]
> Gotchya makes sense. Flashed it and it works, although for all my HTs the rfi seems to be messing with it. It transmits for a sec then disconnects if I have more than 1w out.
> 
> Might be the usb hub vs the AIOC, however. Does make me wish the usb c port pointed down instead of up so the usb cable wasnt next to the antenna.

Interesting.. was it different with the regular firmware? Other than that there have been some reports hinting that the USB cable works as a tiger tail, which introduces high RF currents into the USB Line. Still not sure what to do about it, other than inserting a ferrite into the aioc-to-radio ground line. Still needs to be tested tho





> 1. Does CAT PTT still work when using the automatic ptt firmware? I wouldn't see this being useful much, except maybe when using actual voice, but it'd be a kind of nice feature I suppose. I assume it would still not work for radio programming.

No, CAT PTT is disabled, exactly for the reason you stated.



> 2\. know of any alternatives to dfu-util for Windows? I want to make a Windows batch script to switch firmware version automatically, but requiring users to use Zadig to get libusb seems... rough. Alternatively, perhaps anyone would know how to use wdi-simple to do what zadig does reliably via a script?

I am a Linux user myself, so I don't actually know. From what I have heard, zadig might not even be necessary to install the driver? But I am unsure 

> 3\. would you be interested in approving me as an authorized reseller? I make sure to make each one per the instructions, verify low-resistance connectivity on each connector, and run basic tests on each unit before selling.

Anyone is free to make and sell them. I have not thought about doing an actual authorized seller list. Do you think it's beneficial?

**Comment by ITCMD** [comment]
Looks like firmware cannot be updated with the auto-ptt version.

```
root@lucas-compile-pc:~# dfu-util -d 1209:7388 -a 0 -s 0x08000000:leave -D aioc-fw-1.2.0.bin 
dfu-util 0.11

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: Warning: File too short for DFU suffix
dfu-util: A valid DFU suffix will be required in a future dfu-util release
Opening DFU capable USB device...
Device ID 1209:7388
Run-Time device DFU version 0101
Claiming USB DFU (Run-Time) Interface...
Setting Alternate Interface zero...
Determining device status...
DFU state(0) = appIDLE, status(0) = No error condition is present
Device really in Run-Time Mode, send DFU detach request...
Device will detach and reattach...
Opening DFU USB Device...
Claiming USB DFU Interface...
Setting Alternate Interface #0 ...
Determining device status...
DFU state(10) = dfuERROR, status(10) = Device's firmware is corrupt. It cannot return to run-time (non-DFU) operations
Clearing status
Determining device status...
DFU state(2) = dfuIDLE, status(0) = No error condition is present
DFU mode device DFU version 011a
Device returned transfer size 2048
DfuSe interface name: "Internal Flash  "
Downloading element to address = 0x08000000, size = 0
dfu-util: Last page at 0x07ffffff is not writeable
```

**Comment by ITCMD** [comment]
I found that using a right-angle cable solves the problem. Im selling cables with RFI clips on my website for the AIOCs.

I'd say an authorized seller would be beneficial. That way the buyer knows:
- The seller is following the design they see here
- The seller is not stealing the code or not providing acknowledgments to the author
- Potential users don't have to go searching
- Shows your design is more viable

Also it would certainly help my sales if you linked to it from the github.

**Comment by ITCMD** [comment]
After further testing of this firmware I'd say the automatic ptt is ready for action. Customers agree.

As far as a CLI to change between the two modes of operation, while that'd be super helpful, I'd say it isn't a must since the command to switch firmware versions is just one line of simple code with dfu-util.

However, the hardcoded 10ms time-out could be restrictive in some environments, for example morse code operation. Having some way to configure that is definitely a must-have feature. However, if you're tight on time you could have it as hacky as you want.

For example, you could create an individual version of the firmware for 10ms, 20ms, 60ms, 100ms, 200ms, and 300ms. Yeah, it's hacky and kind of stupid, but it works, and I've learned that shipping _something_ is what's most important.

I'm still working on a Windows TUI that switches between firmware versions, so that could act as a config console for you basically.

Alternatively, some hacky command to change it would also be fine because again a simple program can run that command for the user.

Finally, Having support for a physical switch of some kind to switch firmware, or a potentiometer to change timeout would also be powerful.

Just a few of my thoughts. Let me know what you think!

**Comment by skuep** [comment]
> I found that using a right-angle cable solves the problem. 

That's quite curious, I would not have guessed this to be a radiated EMI problem (99% of EMI problems are conducted EMI in practice e.g. what I have described above). Good information that an angled cable might help. This could be something for a "known issues" or similar section in the README.

> I'd say an authorized seller would be beneficial. 

I'll take that into consideration. Since I am not interested in turning this thing into a "commercial product first - open-source tinkerability second" (truSDX.. cough), I want to keep this kind of advertisement limited. But a list of trusted vendors in the README might be a good idea. I (as the maintainer) would rather like to see the project grow naturally than have a lot of "sales", but being able to buy this thing easily of course helps.

> After further testing of this firmware I'd say the automatic ptt is ready for action. Customers agree.

That sounds good! Out of curiosity, what was the size of group of people testing the feature and with what software? So far I did not receive any feedback from someone else, so I am not so keen on pushing this feature out, yet. Maybe as a preview firmware.

You did say in the pull-request, that programming the radio didn't work. Is that so? Should not be an issue, just the COM PTT (and CM108 PTT) is disabled, and virtual PTT is enabled. (Basically via a pre-processor directive)


> For example, you could create an individual version of the firmware for 10ms, 20ms, 60ms, 100ms, 200ms, and 300ms. 

Nah, that's a lot of work and a big mess. If I, at some point, would like to add another distinction, the number of firmwares I need to generate go up exponentially. I have made some provisions to use vendor calls on the HID endpoint for sending or receiving some small data blocks to/from the AIOC. For linux based operating systems, connecting to this endpoint should be no problem at all. I don't know yet, how difficult this would be on Windows. I assume, the AIOC HID endpoint is listed in the Device Manager as a real HID device? Can you confirm? In that case, maybe it's quite easy to send HID messages to this endpoint from a python script. (I am thinking ``hidapi`` Python module).

> Yeah, it's hacky and kind of stupid, but it works, and I've learned that shipping _something_ is what's most important.

For a product, that's true. This is, so far, just a hobby project ;-)

> I'm still working on a Windows TUI that switches between firmware versions, so that could act as a config console for you basically.

Sounds nice, let me know if I can have a look at it somewhere.

> Just a few of my thoughts. Let me know what you think!

Thanks for all the input, I will think about it!

**Comment by skuep** [comment]
I created a new issue regarding the configuration interface. Your help is appreciated!
https://github.com/skuep/AIOC/issues/30

**Comment by ITCMD** [comment]
Happy I've been able to help out!

I think in this case the Vox functionality will be what many people will want, but the manual ptt is still very useful. Some modes play much better with manual ptt. One extreme example is Morse code, where you want to just leave the ptt on while sending out morse instead of constantly triggering ptt. Neither is a winner over the other, they're both very useful for very different use cases. Quickly being able to switch modes would be powerful.

Have not tested programming, I will. Will also test the HID stuff in Device Manager

**Comment by skuep** [comment]
> I've thought that a few hundred times. It would be better for two reasons: keep the USB cable away from the antenna and wouldn't put stress on the USB cable going down to the PC.

So far, only very few people have had problems with this and I am not sure why. In general the coaxial cable should not have any current running on the outside of the shield, thus the proximity to the USB cable should not be a problem. If it is s problem, your antenna is not working/behaving correctly anyway, so you should fix that issue first. Having said that, I know that in (amateur) radio you are very often satisfied with a non optimal antenna solution (such as a monopole on a galvanically isolated ungrounded HT. I am think if it's possible to flip the layout without much effort to realize a reverse-k1-aioc. Gotta test this.



> BTW.. I've been silently following these two issues around the auto-PTT. I need to try the new firmware; I'm trying to use the AIOC with Allstar. We're going to deploy about 30 of them around the state to support Skywarn operations.

That is really cool! You can try the beta firmware hidden in the issue and report any problems you encounter. I am especially interested in your feedback of the virtual COS. As far as I can tell as an outsider, Allstar is where you need something like this. 

In the future, these functionalities will be integrated in the main firmware and activated and configured (e.g. virtual-COS threshold) using a separate python application.

**Comment by ITCMD** [comment]
> > I've thought that a few hundred times. It would be better for two reasons: keep the USB cable away from the antenna and wouldn't put stress on the USB cable going down to the PC.
> 
> So far, only very few people have had problems with this and I am not sure why. In general the coaxial cable should not have any current running on the outside of the shield, thus the proximity to the USB cable should not be a problem. If it is s problem, your antenna is not working/behaving correctly anyway, so you should fix that issue first. Having said that, I know that in (amateur) radio you are very often satisfied with a non optimal antenna solution (such as a monopole on a galvanically isolated ungrounded HT. I am think if it's possible to flip the layout without much effort to realize a reverse-k1-aioc. Gotta test this.

You're assuming there is a coaxial cable. In my testing, this issue only occurs when using an antenna on the HT (like the included rubber ducky), not an external one attached over a coax cable. When using an external antenna up in a tree or something like that there was no issue.

The AIOC is super compact, making it very attractive for on-the-go HT-based operations.

**Comment by gordonthree** [comment]
I want to test the auto ptt / auto cos with a Alinco mobile radio and Allstar. Any suggestions for connections? The DB9 "data" connector on the radio offers a COR signal  that is active-low and requires a pull-up. It has both 9600 baud and 1200 baud audio inputs and outputs and PTT input that is active-low.

Here's the connections I think I need: DB9 pin 4 audio output connect to AIOC Radio-Spk line. DB9 pin 7 radio PTT connect to AIOC PTT1 (or PTT2?), why is PTT2 listed twice on the schematic? DB9 pin 9 microphone input  connect to AIOC Radio-Mic.

In Allstar I would use the usbradio module? Any hints on settings?

**Comment by Thunter96** [comment]
Is the firmware linked here: https://github.com/skuep/AIOC/files/11524529/aioc-fw-1.2.0-autopttcos.zip

The latest firmware with a software VOX enabled? Apologies if it's a dumb question,  it's not appartent to me if a 'live' version is in the main git repository.

**Comment by rxt1077** [comment]
Regarding Auto-COS, you may want to consider the SIGLEV approach that [svxlink](https://github.com/sm0svx/svxlink) employs. Basically you leave the squelch open and listen to the noise. If it suddenly gets quieter you assume there is a signal. To quote from [their man page](http://www.svxlink.org/doc/man/man5/svxlink.conf.5.html):

> Type NOISE use a bandpass filter in the range of 5 - 5.5kHz (CARD_SAMPLE_RATE >= 16000) or a highpass filter at 3.5kHz (CARD_SAMPLE_RATE = 8000) to estimate the amount of noise present on the signal. If the passband contain a small amount of energy, a strong signal is assumed. If the passband contain more energy, a weaker signal is assumed. The noise detector must be calibrated for the receiver and audio levels you use. This is done using the SIGLEV_SLOPE and SIGLEV_OFFSET configuration variables. See chapter CALIBRATING THE SIGNAL LEVEL DETECTOR below for more information.

This works surprisingly well compared to just trying to detect voice. You have the added benefit of triggering easily when there is no voice, just carrier, and not missing the first syllable because the squelch (Auto-COS in our case) was slow to open.

**Comment by skuep** [comment]
I just pre-released the new v1.3.0 firmware that contains a lot of new features, such as Auto-PTT and Auto-COS. It has to be enabled using some python scripting (for now, that is).
See https://github.com/skuep/AIOC/releases/tag/v1.3.0-rc.1

**Comment by DE8MSH** [comment]
Name it 

CAPTTain -- **CA**tless **PTT**alk**in**

Kidding. ;)

**Comment by skuep** [comment]
> CAPTTain -- **CA**tless **PTT**alk**in**

:-)



> With an OTG cable AIOC device should work as a external soundcard for Android smartphone. So CAPTTain -- uhm -- virtual auto vox PTT should work. Or am I wrong here?

Yeah, pretty much correct. The AIOC should work as a soundcard for your Android phone. I tried it with APRSdroid and it worked, others tried and had mixed results (there are some issues open for this stuff, but it is really hard to debug the problem).

You can try the old testing firmware above or use the v1.3.0-rc.1. However this firmware requires some python magic to select the virtual PTT and store it back to the AIOC. If there is enough interest in trying this out, I can help with that.

**Comment by oe9fwv** [comment]
I would like to try the new 1.3.0rc1 firmware, but I do not know how to configure it for my purpose. I would like to try it with my Anytone and AprsDroid on the Samsung A32. Can you tell me how to configure the script to switch AutoPTT on?

**Comment by oe9fwv** [comment]
> So far, only very few people have had problems with this and I am not sure why. In general the coaxial cable should not have any current running on the outside of the shield,
in an ideal symmetric antenna this is correct, but in real world no antenna is exactly symmetric and there are always more or less sheath waves. (a common mode filter after the antenna should block them)

**Comment by skuep** [comment]
You can find a generic script in the v1.3.0-rc.1 Release page on Github.
Especially for activating AutoPTT can you try this:

````
import sys
import hid
from struct import Struct
from enum import IntEnum, IntFlag

class Register(IntEnum):
    MAGIC = 0x00
    USBID = 0x08
    AIOC_IOMUX0 = 0x24
    AIOC_IOMUX1 = 0x25
    CM108_IOMUX0 = 0x44
    CM108_IOMUX1 = 0x45
    CM108_IOMUX2 = 0x46
    CM108_IOMUX3 = 0x47
    SERIAL_CTRL = 0x60
    SERIAL_IOMUX0 = 0x64
    SERIAL_IOMUX1 = 0x65
    SERIAL_IOMUX2 = 0x66
    SERIAL_IOMUX3 = 0x67
    VPTT_LVLCTRL = 0x82
    VPTT_TIMCTRL = 0x84
    VCOS_LVLCTRL = 0x92
    VCOS_TIMCTRL = 0x94

    
class Command(IntFlag):
    DEFAULTS = 0x10
    RECALL = 0x40
    STORE = 0x80

class PTTSource(IntFlag):
    NONE = 0x00000000
    CM108GPIO1 = 0x00000001
    CM108GPIO2 = 0x00000002
    CM108GPIO3 = 0x00000004
    CM108GPIO4 = 0x00000008
    SERIALDTR = 0x00000100
    SERIALRTS = 0x00000200
    SERIALDTRNRTS = 0x00000400
    SERIALNDTRRTS = 0x00000800
    VPTT = 0x00001000


def read(device, address):
    data = device.get_feature_report(int(address), 5)
    address, value = Struct('<BL').unpack(data)
    return value

def write(device, address, value):
    data = Struct('<BL').pack(address, value)
    device.send_feature_report(data)

def dump(device):
    for r in Register:
        print(f'Reg. {r.value:02x}: {read(device, r.value):08x}')

aioc = hid.Device(vid=0x1209, pid=0x7388)

magic = Struct("<L").pack(read(aioc, Register.MAGIC))

if (magic != b'AIOC'):
    sys.exit(-1)

print(f'Manufacturer: {aioc.manufacturer}')
print(f'Product: {aioc.product}')
print(f'Serial No: {aioc.serial}')
print(f'Magic: {magic}')

if True:
    # Load the hardware defaults
    print(f'Loading Defaults...')
    write(aioc, 0, Command.DEFAULTS)

if True:
    # Dump all known registers
    dump(aioc)

ptt1_source = PTTSource(read(aioc, Register.AIOC_IOMUX0))
ptt2_source = PTTSource(read(aioc, Register.AIOC_IOMUX1))

print(f'Current PTT1 Source: {str(ptt1_source)}')
print(f'Current PTT2 Source: {str(ptt2_source)}')

if False:
    # Swap PTT1/PTT2
    ptt1_source, ptt2_source = ptt2_source, ptt1_source
    print(f'Setting PTT1 Source to {str(ptt1_source)}')
    write(aioc, Register.AIOC_IOMUX0, ptt1_source)
    print(f'Setting PTT2 Source to {str(ptt2_source)}')
    write(aioc, Register.AIOC_IOMUX1, ptt2_source)

    print(f'Now PTT1 Source: {str(PTTSource(read(aioc, Register.AIOC_IOMUX0)))}')
    print(f'Now PTT2 Source: {str(PTTSource(read(aioc, Register.AIOC_IOMUX1)))}')

if True:
    # Set to AutoPTT on PTT1
    write(aioc, Register.AIOC_IOMUX0, PTTSource.VPTT)


if False:
    # Set USB VID and PID (use with caution. Will need changes above to be able to re-configure the AIOC)
    write(aioc, Register.USBID, (0x1209 << 0) | (0x7388 << 16))
    print(f'Now USBID: {read(aioc, Register.USBID):08x}')

if True:
    # Store settings into flash
    print(f'Storing...')
    write(aioc, 0, Command.STORE)
````

You need to install the ``hid`` package (https://pypi.org/project/hid/) e.g. using pip. Let me know how it works out, it's best if you include the output of the script.

**Comment by OE9SAU** [comment]
Hello Simon, i tried out your script and got this output. 
Manufacturer: AIOC
Product: AIOC HID
Serial No: b59d132e
Traceback (most recent call last):
  File "D:\Neuer Ordner\Test.py", line 41, in <module>
    print(f'Current PTT1 Source: {str(PTTSource(read(aioc, Register.PTT1CTRL)))}')
  File "D:\Neuer Ordner\Test.py", line 27, in read
    data = device.get_feature_report(int(address), 5)
  File "C:\Users\Sauti\AppData\Local\Programs\Python\Python310\lib\site-packages\hid\__init__.py", line 232, in get_feature_report
    size = self.__hidcall(
  File "C:\Users\Sauti\AppData\Local\Programs\Python\Python310\lib\site-packages\hid\__init__.py", line 190, in __hidcall
    raise HIDException(err)
hid.HIDException: Get Input/Feature Report DeviceIoControl: (0x00000001) Unzulässige Funktion.

**Comment by skuep** [comment]
Thanks for testing.. this looks like you're the first one on Windows to try this. From a quick search the problem is, that Windows is really strict about the HID reports. I think the AIOC firmware currently does not list the "feature reports" (that are used for transferring configuration data) in its own HID report descriptor. Which windows notices as soon as you try to request a feature report and blocks you from doing so. Interesting, it appears that Linux doesn't care about this 😁 I will try to update the firmware in the near future and release an RC.2 version.

**Comment by OE9SAU** [comment]
Thank you for your feedback and the adapted new FW in the near future.

**Comment by skuep** [comment]
Can you have a quick test of this new firmware? I added an entry in the report descriptors, but I am not entirely sure if Windows is satisfied with this. If not, I need to spin up a Windows machine and dig deeper.

Happy easter holidays! ;-)

[aioc-fw-1.3.0-rc.1-featurereport.bin.zip](https://github.com/skuep/AIOC/files/14816273/aioc-fw-1.3.0-rc.1-featurereport.bin.zip)

**Comment by OE9SAU** [comment]
Will test asap today evening.

**Comment by OE9SAU** [comment]
Hi Simon, unfortunately the test was negative.  Same output.

_Traceback (most recent call last):
  File "D:\Neuer Ordner\AIOC_FW1.3.py", line 59, in <module>
    magic = Struct("<L").pack(read(aioc, Register.MAGIC))
  File "D:\Neuer Ordner\AIOC_FW1.3.py", line 45, in read
    data = device.get_feature_report(int(address), 5)
  File "C:\Users\Sauti\AppData\Local\Programs\Python\Python310\lib\site-packages\hid\__init__.py", line 232, in get_feature_report
    size = self.__hidcall(
  File "C:\Users\Sauti\AppData\Local\Programs\Python\Python310\lib\site-packages\hid\__init__.py", line 190, in __hidcall
    raise HIDException(err)
hid.HIDException: Get Input/Feature Report DeviceIoControl: (0x00000057) Falscher Parameter._

Regards Martin

**Comment by skuep** [comment]
It's not the same error 😁 but it looks like I have to be more specific with the descriptor.. I will set up a Windows station and need to play around a bit.

In the meantime you could use the virtual PTT test firmware I posted earlier in this issue.

**Comment by OE9SAU** [comment]
Tested that virtual PTT test firmware but without success. Maybe i toke the wrong one? martin

**Comment by OE9SAU** [comment]
Hello Simon, any further update for us?

**Comment by skuep** [comment]
> Hello Simon, any further update for us?

Sorry for the late reply, I am currently swamped with work.

What does "without success" mean? No PTT action? Which one did you use? 

This should be the correct one, if I am not mistaken:
https://github.com/skuep/AIOC/files/11524529/aioc-fw-1.2.0-autopttcos.zip

**Comment by OE9SAU** [comment]
Hi Simon, Work comes first, clearly. Thank you here for your commitment. "without success" mean? No PTT action? YES. I will try the linked one and report back to you. Many thanks martin

**Comment by OE9SAU** [comment]
> Hi Simon, Work comes first, clearly. Thank you here for your commitment. "without success" mean? No PTT action? YES. I will try the linked one and report back to you. Many thanks martin

Update:
With the linked FW the AUTOPTT works fine with VARA FM and Aprsdroid. Many Thanks my friend. 73 de OE9SAU + OE9FWV

**Comment by skuep** [comment]
That's cool! Now I got to work on making the new firmware work on Windows so that you can also configure the thresholds for Auto PTT 😁

**Comment by W1BTR** [comment]
Back into the swing of things for this project again. Once you have an updated Windows and linux script let me know, happy to test on both.

Obviously when work, allows the extra time! :D

**Comment by stgapr** [comment]
I'm waiting for my AIOC module shipping from shenzhen. In this while, I wonder if anyone tried to use AIOC to made FT8 possible by using FT8CN and UV-K5 ?

**Comment by ITCMD** [comment]
> hi Simon, I have to add a comment to the AUTOPTT feature. I found out that in APRSdroid outgoing beacons are not decoded when I use AutoPTT with the default settings in AprsDroid. When I manually press the PTT on the handheld, beacons are decoded by the digipeater. I think it must be the Tx delay of the AutoPTT. There is a setting called frame-sync-prefix in the aprsdroid connection settings. Default is 200msec. I tried to set it higher, to 500 msec, and this seemed to help. The frame-sync-prefix can be distinguished by monitoring the signal, and I think if you can hear the prefix, it is long enough. It might be also dependent from the transceiver you are using.

This is an issue with all automatic ptt methods (Aioc, signalink, custom circuit, etc), as the device cant predict when it will receive audio.

Luckily Aprsdroid has a built in feature for this called Frame sync prefix:
![Screenshot_20240612_083819_APRSdroid](https://github.com/skuep/AIOC/assets/32961763/96cb4ff4-886f-4867-a9f7-16d07324f7f0)

**Comment by oe9fwv** [comment]
@ITCMD that's exaxtly what I wrote in my comment: :-)
"there is a setting called frame-sync-prefix in the aprsdroid connection settings."

**Comment by ITCMD** [comment]
Would it be possible to still allow serial control over PTT while running in automatic mode, or alternatively allowing it to at least control PTT2?

**Comment by skuep** [comment]
@ITCMD sorry for the late reply.. you can theoretically select multiple sources for the PTT signal, such as Auto PTT and serial. All enables sources will be logically or'ed

**Comment by georges** [comment]
I flashed the [aioc-fw-1.2.0-autopttcos.zip](https://github.com/skuep/AIOC/files/11524529/aioc-fw-1.2.0-autopttcos.zip) to test the auto PTT. I can't seem to get it to work. The audio interface shows up, and I can record audio fine. When I send audio, there is no PTT, no red LED. 

Is there a setting that's required? I tried the aioc-util but it failed to read the device (tried both on Mac and Rasbpi)

**Comment by skuep** [comment]
If I am not mistaken, the code for AutoPTT schould now be in the latest official release, so no need for the special firmware. However, yes, it is necessary to enable the AutoPTT feature (by default, PTT is asserted either using the CM108 interface or the specific RTS/DTR combination).

So aioc-util is kind of necessary to achieve this. What was the problem with using it?

**Comment by W1BTR** [comment]
Likely the issue is related to #91 - if that's the same script. It only works on 32 bit raspbian

**Comment by georges** [comment]
It was not clear which version has AutoPTT since there is a branch open and this issue is also still open :)

```
$ python3 aioc-util.py --auto-ptt1
Traceback (most recent call last):
  File "/home/pi/aioc-util/aioc-util.py", line 602, in <module>
    main()
  File "/home/pi/aioc-util/aioc-util.py", line 333, in main
    magic = Struct("<L").pack(read(aioc, Register.MAGIC))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/aioc-util/aioc-util.py", line 118, in read
    data = device.get_feature_report(0, 7)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/aioc-util/venv/lib/python3.11/site-packages/hid/__init__.py", line 235, in get_feature_report
    size = self.__hidcall(
           ^^^^^^^^^^^^^^^
  File "/home/pi/aioc-util/venv/lib/python3.11/site-packages/hid/__init__.py", line 193, in __hidcall
    raise HIDException(err)
hid.HIDException: ioctl (GFEATURE): Broken pipe
```


This is the error I get. I'm running indeed 64bit

```
$ uname -a
Linux digipi 6.1.77-v8+ #1730 SMP PREEMPT Thu Feb  8 15:26:11 GMT 2024 aarch64 GNU/Linux
```

Suggestions?

**Comment by skuep** [comment]
> It was not clear which version has AutoPTT since there is a branch open and this issue is also still open :)

That is totally true and to be honest I am not sure myself at the moment 😁

I think the issue you are having is that the his interface changed in recent versions and thus is not compatible to the aioc-util... Could you try the latest firmware?

**Comment by georges** [comment]
Ok flashed 1.4.1 firmware, aioc-util is now behaving properly and I was able to set AutoPTT to on. Can confirm AutoPTT is now working. 

I made some change in my code and was able to get AIOC to work with the built-in packet modem in RadioMail on iOS. W00t! More testing needed but looking good so far.

**Comment by georges** [comment]
I have test builds of RadioMail (https://radiomail.app) and Packet Commander (https://packetcommander.com) that now include AIOC support for the built-in packet modem.

If you use iOS and would like to test this functionality, send me a DM and I’ll add you to TestFlight.

**Comment by skuep** [comment]
> Ok flashed 1.4.1 firmware, aioc-util is now behaving properly and I was able to set AutoPTT to on. Can confirm AutoPTT is now working.
> 
> I made some change in my code and was able to get AIOC to work with the built-in packet modem in RadioMail on iOS. W00t! More testing needed but looking good so far.

Awesome! We didn't have a lot of testers for the AutoPTT feature, so that's why everything is a bit obscure and undocumented at the moment. It seems like interest is not so high after all, but nevertheless it's good to hear that everything is working with the most current firmware release.

I am curious what changes you need to make? Did you know that by default, the AIOC can be operated (PTT included) using the CM108 interface?

**Comment by georges** [comment]
On iOS, Apple does not allow applications to access USB directly, so apps cannot control external devices. The AIOC presents itself only as a sound card, limiting interaction to audio playback and recording.

Some adapters, such as the DigiRig Lite, use the right audio channel to control PTT by sending a dedicated control signal. This enables precise, application-level control over the PTT lifecycle.

The AIOC does not support this approach. Since it presents as a mono device, I removed the control tone to ensure that only the modulation signal is transmitted. In practice, this works ok because the AIOC responds quickly enough. However, there may be radios that require PTT to be asserted slightly earlier, which could expose a limitation with this approach. I tested on a TH-D74 only.

**Comment by skuep** [comment]
That's interesting! In theory we could mimic the same behaviour with a second audio channel, but if I remember correctly, things already are crowded in terms of available USB endpoint memory on the microcontroller.

However we could use other features of a standard soundcard. The standard has provisions in the protocol to tell the device e.g. to switch on or off a microphone amplifier. If the MacOS API allows sending such "standardized" commands, we could hijack one of them theoretically!

**Comment by georges** [comment]
I don't believe there is support for anything like that on the audio interface. Aside from another audio channel, the best bet would be exposing some BLE characteristic. There *might* be a way to send requests to a HID device via CoreHID. I don't know if that can be done as is, or if iOS requires more permissions. Maybe I'll just create a small prototype to play around with that.

**Comment by georges** [comment]
No go. CoreHID is macOS only. Seems that indeed the only way to access usb devices on iOS is to go thru the Mfi Apple certification process.

**Comment by Nehem11e** [comment]
I am testing RadioMail and Packet Commander on iOS with the AIOC. As Georges stated it’s only using the AIOC sound interface so I need to get the auto PTT working. I have been trying on my windows machine but an hit similar roadblocks with HID with the aioc-util tool. 

Has anyone else gotten this working on windows? I will go try it with another OS, but can also do some dedicated Windows testing if needed.

Edit:
My old Mac for the win. aioc-utils worked for me on the mac. Now I able to connect Iphone -> lightening usbc OTG adapter-> USB C cable -> AIOC -> HT

I can setup Packet Commander on the iPhone (the volume meter to adjust HT squelch off static into the sweet spot with HT volume control is nice, I haven’t looked at the v1.2 hardware changes that can also adjust volume levels) Also the tx tone test with variable frequency works nicely.

Once Packet Commander is Testing Properly, i setup Radio Mail to use Packet Commander. From Radio Mail I initiate a connection to a local Station and with a second HT tuned to the same frequency I hear packet waveforms. So it all seems to be working! I am just not close enough to the station for it to hear me. Official Test tomorrow!

**Comment by skuep** [comment]
Pretty cool! Yeah unfortunately the hid package often make problems. We should switch to something else in the future probably...
